// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spZ_5_3f_to_3_0f_L173 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spZ_5_3f_to_3_0f_L173()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State2,
                GrabState = State.State1,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (2, 1): not holding, XY is at pickup, and Z is moving vertically for pickup."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=8.3, spY=5.5, spZ=3
        // posX=8.299902, posY=5.4999084, posZ=3.0011845
        // counter=0, exitBox=0
    }
}
