// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_3_1f_to_3_0f_L128 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_3_1f_to_3_0f_L128()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                StopExitBox = 1,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.MisalignmentPallet,
                GrabReleaseOperations = new[]
                {
                    new PickPlaceXYZGrabReleaseOperation(3f, 5.3f, 5f, 3.1f, 5.3f, 5f, true, true),
                },
                Reason = @"Stage 1 state identification skipped for label 'misalignment_pallet'; defer to recovery module identification. Stage 2 recovery module: misalignment_pallet module selected. Misalignment pallet recovery will run 1 configured grab-release operations before benign resume."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=True
        // spX=3, spY=5.3, spZ=5
        // posX=3.0001113, posY=5.3000793, posZ=4.9999046
        // counter=3, exitBox=0
    }
}
