// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_pickingState_State4_to_State5_L133 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_pickingState_State4_to_State5_L133()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State3,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (3, 0): holding, moving horizontally toward placement, and Z is 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=False
        // spX=8.3, spY=5.5, spZ=0
        // posX=6.556199, posY=5.487137, posZ=0
        // counter=0, exitBox=0
    }
}
