// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_pickingState_State5_to_State2_L152 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_pickingState_State5_to_State2_L152()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State5,
                GrabState = State.State0,
                Counter = 2,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (5, 0): not holding, XY is at a place location, and Z is moving vertically after release."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=True
        // spX=3.1, spY=5.3, spZ=5
        // posX=3.1000834, posY=5.3000793, posZ=5.0019217
        // counter=2, exitBox=0
    }
}
