// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_grabState_State2_to_State0_L178 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_grabState_State2_to_State0_L178()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                StopExitBox = 1,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.Underflow,
                Reason = @"Stage 1 state identification skipped for label 'underflow'; defer to recovery module identification. Stage 2 recovery module: underflow module selected. Underflow counter override: counter = 0. Underflow exitBox override: exitBox = 0. Underflow continuation: resume from State (0, 0) after pallet reaches loading area."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=True, detected=False
        // partConveyorForward=False, boxConveyorForward=True, exitConveyor=False
        // grab=False, c=True
        // spX=3.1, spY=5.3, spZ=0
        // posX=3.1001012, posY=5.3000793, posZ=0
        // counter=0, exitBox=1
    }
}
