// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_8_3f_to_6_8f_L98 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_8_3f_to_6_8f_L98()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                OverrideCounter = true,
                RecoveryCounter = 0,
                ExitBox = 0,
                StopExitBox = 2,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.MisalignmentBeltConveyor,
                Reason = @"Stage 1 state identification skipped for label 'misalignment_beltconveyor'; defer to recovery module identification. Stage 2 recovery module: misalignment_beltconveyor module selected. Misalignment belt conveyor counter override: counter = 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=6.8, spY=5.5, spZ=5.3
        // posX=6.80025, posY=5.4999084, posZ=5.2938747
        // counter=0, exitBox=0
    }
}
