// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_posZ_to_neg_1_0f_L146 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_posZ_to_neg_1_0f_L146()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State4,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (4, 0): holding, XY is at a place location, and Z is moving vertically for placement."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=False
        // spX=3.1, spY=3.8, spZ=10
        // posX=3.1001012, posY=3.8000793, posZ=10
        // counter=0, exitBox=0
    }
}
