// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_boxAtPlace_neg_L222 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_boxAtPlace_neg_L222()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (0, 0): not holding, XY is at pickup or one of the three place locations, and Z is 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=True, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=0, spY=0, spZ=0
        // posX=0, posY=0, posZ=0
        // counter=0, exitBox=0
    }
}
