// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_posY_to_5_0f_L132 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_posY_to_5_0f_L132()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State3,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (3, 0): holding, moving horizontally toward placement, and Z is 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=False
        // spX=3.1, spY=3.8, spZ=0
        // posX=3.1001012, posY=3.8000793, posZ=0
        // counter=0, exitBox=0
    }
}
