// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_3_1f_to_neg_1_0f_L121 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_3_1f_to_neg_1_0f_L121()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State3,
                GrabState = State.State0,
                Counter = 1,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"Fallback: grab is true, so recover to State (3, 0) and continue carrying toward placement."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=False
        // spX=-1, spY=6.7, spZ=0
        // posX=0, posY=6.6999207, posZ=0
        // counter=1, exitBox=0
    }
}
