// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_3_1f_to_4_28f_L121 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_3_1f_to_4_28f_L121()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                StopExitBox = 1,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.MisalignmentSecondBox,
                GrabReleaseOperations = new[]
                {
                    new PickPlaceXYZGrabReleaseOperation(3.1f, 5.3f, 5f, 8.3f, 5.5f, 0.2f, true, false),
                    new PickPlaceXYZGrabReleaseOperation(4.280108f, 6.699921f, 9.97726f, 3.1f, 6.7f, 10f, false, false),
                    new PickPlaceXYZGrabReleaseOperation(8.3f, 5.5f, 0.2f, 3.1f, 5.3f, 5f, false, true),
                },
                Reason = @"Stage 1 state identification skipped for label 'misalignment_second_box'; defer to recovery module identification. Stage 2 recovery module: misalignment_second_box module selected. Recovery log classifier selected 'misalignment_second_box' from 'PickPlaceXYZ_spX_3_1f_to_4_28f_L121.csv' with rho=0.8901279. Misalignment box inputs loaded from last row of enhanced CSV 'PickPlaceXYZ_spX_3_1f_to_4_28f_L121.csv'. Misalignment box recovery will run 3 configured grab-release operations before benign resume."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=True
        // spX=3.1, spY=5.3, spZ=5
        // posX=3.1001012, posY=5.3000793, posZ=5.000167
        // counter=3, exitBox=0
    }
}
