// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spZ_0_0f_to_10f_L157 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spZ_0_0f_to_10f_L157()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 1,
                ExitBox = 0,
                StopExitBox = 2,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.Overflow,
                SafeGrabCompletionThreshold = 4,
                Reason = @"Stage 1 state identification skipped for label 'overflow'; defer to recovery module identification. Stage 2 recovery module placeholder: overflow module selected. Overflow start state override: grab is false, start from State (0, 0) with safe grab threshold = 4."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=True, boxAtPlace=False, detected=False
        // partConveyorForward=True, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=8.3, spY=5.5, spZ=5.3
        // posX=8.298537, posY=5.4999084, posZ=5.3007936
        // counter=1, exitBox=0
    }
}
