// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_3_1f_to_8_0f_L128 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_3_1f_to_8_0f_L128()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State3,
                GrabState = State.State0,
                Counter = 2,
                ExitBox = 0,
                StopExitBox = 2,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.Overflow,
                SafeGrabCompletionThreshold = 2,
                Reason = @"Stage 1 state identification skipped for label 'overflow'; defer to recovery module identification. Stage 2 recovery module placeholder: overflow module selected. Overflow start state override: grab is true, start from State (3, 0) with safe grab threshold = 2."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=True, boxAtPlace=False, detected=True
        // partConveyorForward=True, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=True
        // spX=8, spY=5.3, spZ=5
        // posX=7.999752, posY=5.3000793, posZ=3.130269
        // counter=2, exitBox=0
    }
}
