// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_3_1f_to_2_21f_L128 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_3_1f_to_2_21f_L128()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                StopExitBox = 1,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.MisalignmentThirdBox,
                GrabReleaseOperations = new[]
                {
                    new PickPlaceXYZGrabReleaseOperation(2.210101f, 5.300079f, 4.973598f, 3.1f, 5.3f, 5f, true, true),
                },
                Reason = @"Stage 1 state identification skipped for label 'misalignment_third_box'; defer to recovery module identification. Stage 2 recovery module: misalignment_third_box module selected. Recovery log classifier selected 'misalignment_third_box' from 'PickPlaceXYZ_spX_3_1f_to_2_21f_L128.csv' with rho=0.89408803. Misalignment box inputs loaded from last row of enhanced CSV 'PickPlaceXYZ_spX_3_1f_to_2_21f_L128.csv'. Misalignment box recovery will run 1 configured grab-release operations before benign resume."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=True
        // spX=2.21, spY=5.3, spZ=5
        // posX=2.210101, posY=5.3000793, posZ=5.000725
        // counter=3, exitBox=0
    }
}
