// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spY_5_5f_to_6_9f_L99 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spY_5_5f_to_6_9f_L99()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                OverrideCounter = true,
                RecoveryCounter = 0,
                ExitBox = 0,
                StopExitBox = 2,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.MisalignmentBeltConveyor,
                Reason = @"Stage 1 state identification skipped for label 'misalignment_beltconveyor'; defer to recovery module identification. Stage 2 recovery module: misalignment_beltconveyor module selected. Misalignment belt conveyor counter override: counter = 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=8.3, spY=6.9, spZ=5.3
        // posX=8.299902, posY=6.8999176, posZ=5.291848
        // counter=0, exitBox=0
    }
}
