// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_pickingState_State0_to_State4_L160 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_pickingState_State0_to_State4_L160()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 1,
                ExitBox = 0,
                StopExitBox = 1,
                StateIdentificationSatisfied = false,
                RecoveryModule = RecoveryModule.Underflow,
                Reason = @"Stage 1 state identification skipped for label 'underflow'; defer to recovery module identification. Stage 2 recovery module: underflow module selected. Recovery log classifier selected 'underflow' from 'PickPlaceXYZ_pickingState_State0_to_State4_L160.csv' with rho=0.05. Underflow state override: grab is false, resume from State (0, 0). Underflow counter override: counter = 0. Underflow exitBox override: exitBox = 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=3.1, spY=3.8, spZ=0
        // posX=3.100119, posY=3.8000793, posZ=0
        // counter=398, exitBox=0
    }
}
