// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_pickingState_State0_to_State5_L160 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_pickingState_State0_to_State5_L160()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 1,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (0, 0): not holding, XY is at pickup or one of the three place locations, and Z is 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=3.1, spY=3.8, spZ=0
        // posX=3.100119, posY=3.8000793, posZ=0
        // counter=1, exitBox=0
    }
}
