// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spY_5_3f_to_neg_1_0f_L129 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spY_5_3f_to_neg_1_0f_L129()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State3,
                GrabState = State.State0,
                Counter = 2,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (3, 0): holding, moving horizontally toward placement, and Z is 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=True
        // spX=3.1, spY=-1, spZ=0
        // posX=3.1001012, posY=0, posZ=0
        // counter=2, exitBox=0
    }
}
