// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_posZ_to_neg_1_0f_L197 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_posZ_to_neg_1_0f_L197()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State2,
                GrabState = State.State3,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (2, 3): holding, XY is at pickup, Z is moving vertically, and retract command is active."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=False
        // spX=8.3, spY=5.5, spZ=0
        // posX=8.299919, posY=5.4999084, posZ=0
        // counter=0, exitBox=0
    }
}
