// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spZ_5_3f_to_neg_1_0f_L173 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spZ_5_3f_to_neg_1_0f_L173()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State1,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (1, 0): not holding, moving horizontally, and Z is 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=8.3, spY=5.5, spZ=-1
        // posX=8.299902, posY=5.4999084, posZ=0
        // counter=0, exitBox=0
    }
}
