// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spY_3_8f_to_11_0f_L117 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spY_3_8f_to_11_0f_L117()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State3,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"Fallback: grab is true, so recover to State (3, 0) and continue carrying toward placement."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=True
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=True, c=False
        // spX=3.1, spY=11, spZ=0
        // posX=3.100119, posY=9.999908, posZ=0
        // counter=0, exitBox=0
    }
}
