// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_spX_8_3f_to_11_0f_L98 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_spX_8_3f_to_11_0f_L98()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State0,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = true,
                RecoverySpZ = 0f,
                Reason = @"Fallback: grab is false, so recover to State (0, 0) and command SP Z to 0."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=11, spY=5.5, spZ=0
        // posX=9.99991, posY=5.4999084, posZ=0
        // counter=0, exitBox=0
    }
}
