// Auto-generated by Program_TestRecovery.
// This class is compiled at runtime and loaded after Factory I/O is paused.

namespace Controllers
{
    public sealed class Recovery_PickPlaceXYZ_pickingState_State2_to_State3_L104 : Recovery_PickPlaceXYZ
    {
        public Recovery_PickPlaceXYZ_pickingState_State2_to_State3_L104()
            : base(new PickPlaceXYZRecoveryDecision
            {
                PickingState = State.State5,
                GrabState = State.State0,
                Counter = 0,
                ExitBox = 0,
                OverrideSpZ = false,
                RecoverySpZ = 0f,
                Reason = @"State (5, 0): not holding, XY is at a place location, and Z is moving vertically after release."
            })
        {
        }

        // Paused snapshot used to make the decision:
        // partAtPlace=False, boxAtPlace=False, detected=False
        // partConveyorForward=False, boxConveyorForward=False, exitConveyor=False
        // grab=False, c=False
        // spX=3.1, spY=3.8, spZ=5.3
        // posX=3.1001012, posY=3.8000793, posZ=5.300441
        // counter=0, exitBox=0
    }
}
