<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Platform>x64</Platform>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
	<StartupObject>Controllers.Program_Recovery</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Engine IO">
      <HintPath>..\..\lib\Engine IO.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ScreenRecorderLib" Version="6.5.1" />
  </ItemGroup>

</Project>
